### ISSUE TITLE
Issue with Example (echo_server)

### ISSUE THREAD

**Issue by svetly** [kenhkan/noflo-woute#2]
First let me say thank you for updating the noflo-woute documentation. Easy to follow, I was able to get the example running (echo_server).

However, there seems to be an issue. When I make requests to given paths as per your instructions, I do not get a response back. Terminal/browser gets stuck waiting for the response.

Might it be a problem with the webserver/BodyParser component?

Below is where the debugger gets stuck:

Svet:echo_server Svetly$ ./node_modules/.bin/noflo --debug graphs/main.fbp
DATA -> LISTEN Server() CONN
DATA -> LISTEN Server() DATA
DATA -> LISTEN Server() DISC
DATA -> METHOD MatchAllPosts() CONN
DATA -> METHOD MatchAllPosts() DATA
DATA -> METHOD MatchAllPosts() DISC
DATA -> MATCH MatchEcho() CONN
DATA -> MATCH MatchEcho() DATA
DATA -> MATCH MatchEcho() DISC
DATA -> MATCH MatchEmptyBody() CONN
DATA -> MATCH MatchEmptyBody() DATA
DATA -> MATCH MatchEmptyBody() DISC
DATA -> STRING SendMissingStatus() CONN
DATA -> STRING SendMissingStatus() DATA
DATA -> STRING SendMissingStatus() DISC
Server() REQUEST -> IN BodyParser() CONN 

Do you know how to get past this?

Thanks!

**Comment by kenhkan** [comment]
Hi @svetly! Thanks for trying it out!

The problem is actually much more subtle than that. There was a commit to the [Server component](https://github.com/noflo/noflo-webserver/blob/master/components/Server.coffee#L38) that moved request disconnection to take place when the server closes down rather than upon end of request submission, which was the case and is also the protocol that noflo-webserver middlewares use.

I've submitted a [PR](https://github.com/noflo/noflo-webserver/pull/4) to the repo. Meanwhile, use my fork's [master branch](https://github.com/kenhkan/noflo-webserver). You may also just do `npm install noflo-woute` again on a clean directory as I've updated noflo-woute to use my fork until this is resolved.

Thanks for submitting this issue! I was using a linked version of an older noflo-webserver so this bug didn't surface. It should now work though.

**Comment by kenhkan** [comment]
Hey @svetly. Did it work out for you? I'm a little worried that I'm not catching all the bugs because I've been using a heavily modded collection of packages. It'd be great if you could report more bugs if you see any. Thanks!
