### ISSUE TITLE
Subsequent requests do not match, only first one/ one time after network has been created

### ISSUE THREAD

**Issue by semanticdreamer** [kenhkan/noflo-woute#4]
Not sure if it's a bug or if I'm missing something, but I do get the expect behaviour of my graph (anything besides POST to /app should ALWAYS respond with 404) only for the first request after network has beed created not for any subsequent request.

Here's the graph I'm refering to: https://gist.github.com/semanticdreamer/7098171

What am I missing?

Thx for looking into this.

**Comment by semanticdreamer** [comment]
Well, (of course) I was missing something.

Fixed graph in comments: https://gist.github.com/semanticdreamer/7098171#comment-943923

**Comment by kenhkan** [comment]
Sorry @semanticdreamer somehow your issue escaped my inbox. Thanks for posting the solution!

And yea, because a request needs to be fulfilled with all the necessary parts like status, body, etc it's easy to introduce leaks by accident using ports. This has bugged me before and the only solution I can come up with is to directly manipulate the request/response object. If you have any idea on how to best handle this, feel free to build on top of noflo-woute! :D
